### PR TITLE
Fix payment stream usd value

### LINKED ISSUE #2408: Display correct USD value for payment streams
USD value of payment streams are not appearing for streams with assets with known USD values.

See: https://app.decentdao.org/roles/details?dao=eth:0xB98d45F9021D71E6Fc30b43FD37FB3b1Bf12c064&hatId=0x0000003100010002000000000000000000000000000000000000000000000000

image_360

### PR DESCRIPTION
**Pull request by adamgall**
Fixes #2408 

viem's `getAddress` code:
screenshot_2024-10-11_at_2 31 46___pm

our code in the place where we're pulling in payment stream data:
screenshot_2024-10-11_at_2 32 31___pm

results in a checksummed address that doesn't follow "normal" checksumming patterns:
Screenshot 2024-10-11 at 2 33 31 PM

### CODE REVIEW

File: src/hooks/DAO/loaders/useHatsTree.ts [hunk 1]
```diff
@@ -196,10 +196,7 @@ const useHatsTree = () => {
                   streamId: lockupLinearStream.id,
                   contractAddress: lockupLinearStream.contract.address,
                   asset: {
-                    address: getAddress(
-                      lockupLinearStream.asset.address,
-                      lockupLinearStream.asset.chainId,
-                    ),
+                    address: getAddress(lockupLinearStream.asset.address),
```
Comment (adamgall) [inline src/hooks/DAO/loaders/useHatsTree.ts:199]: This is the only actual fix for the issue. All of the other changes in this PR are related to simply cleaning up other instances where we're calling `getAddress` but don't need to be.

**Review by Da-Colon — APPROVED** [review]

**Review by DarksightKellar — APPROVED** [review]

**Review by mudrila — APPROVED** [review]
