### PR TITLE
Treasury page fixes

### LINKED ISSUE #2367: Only received txs on Treasury Page
Steps to see the problem:
 
- Check out [this safe's treasury page](https://app.dev.decentdao.org/treasury?dao=sep:0xa042F2b97855f72c4714B9E5ff9d603D2EE7F078). Nothing obvious amiss here, except:
  - There are only "Received" txs

### PR DESCRIPTION
**Pull request by DarksightKellar**
Closes #2367

Also updated some logic around treasury loading indication, which was half-implemented and missing.

### CODE REVIEW

**Review by mudrila — APPROVED** [review]
Code-wise - looks good, haven't tested it though

**Comment by adamgall** [comment]
@DarksightKellar does this PR fix all of the issues described in #2367 ?

**Comment by DarksightKellar** [comment]
> @DarksightKellar does this PR fix all of the issues described in #2367 ?

Oh no my bad. I've updated the description

**Comment by adamgall** [comment]
@DarksightKellar are the issues described in https://github.com/decentdao/decent-interface/issues/2367 present on `develop`? if so, can this branch target `develop`?

File: src/components/pages/DAOTreasury/components/Transactions.tsx [hunk 1]
```diff
@@ -112,13 +113,17 @@ function EmptyTransactions() {
...
-    return null;
+  if (transfers === null) {
+    return (
+      <Center w="100%">
+        <BarLoader />
+      </Center>
+    );
   }
-  if (transfers.length === 0 && transfersLoaded) return <EmptyTransactions />;
+  if (transfers.length === 0) return <EmptyTransactions />;
```
Comment (adamgall) [inline src/components/pages/DAOTreasury/components/Transactions.tsx:126]: You tested this logic on a Safe with zero transactions?

**Review by adamgall — APPROVED** [review]

File: src/components/pages/DAOTreasury/components/Transactions.tsx (hunk 1 above)
Comment (DarksightKellar) [reply src/components/pages/DAOTreasury/components/Transactions.tsx:126]: Yep. Logic works between loading-but-will-be-0, loading-and-will-be-non-zero, loaded-and-0, and loaded-and-non-zero states. `transfers === null` denotes loading (or rather, "nothing has been loaded yet, since that is its initial state"). 

It was either that or make use of `transfersLoaded`. I considered both but decided if I was going to use `transfersLoaded`, then the `null` initial `transfers` state makes no sense and will have to be changed to an empty array initial state, but then _that_ in itself will require more logic checks to differentiate "empty but still loading" vs "empty AND loaded" states.

**Comment by DarksightKellar** [comment]
Got 2 approvals -- gonna merge this 🚀
