### PR TITLE
Fix token import supply allowing alphanumeric input

### LINKED ISSUE #1981: Votes Token Import allows numeric input
See [this comment and todo](https://github.com/decentdao/decent-interface/pull/1979#discussion_r1628067101) for context

Edit from Adam: This issue should be "disallow all input in the given input field"

### PR DESCRIPTION
**Pull request by DarksightKellar**
Closes #1981

edit from Adam: After more product review, this PR should actually be a different implementation. Instead of only allowing numeric input for the given input field, it should _disallow all input_.

### CODE REVIEW

**Review by adamgall — APPROVED** [review]

**Review by Da-Colon — APPROVED** [review]

**Comment by tomstuart123** [comment]
No need to wait for my review here as the original comment seems very dev/code focused.

**Comment by adamgall** [comment]
@tomstuart123 , if you do have time, would be good to have Product signoff on this.

When creating DAO, importing existing token:
- on develop right now, can input alpha characters
- on this PR, should only be able to input numeric characters

**Comment by tomstuart123** [comment]
Nice, token supply # is now non-editable. Thanks @DarksightKellar .

One design thought: 
--> If it can't be edited, shouldn't it be greyed out for the user? 
Screenshot 2024-06-14 at 16 31 10

--> E.g. similar to when we modify governance of a safe and the user can't change a safeName
Screenshot 2024-06-14 at 16 29 14

File: src/components/DaoCreator/formComponents/VotesTokenImport.tsx [hunk 1]
```diff
@@ -48,9 +48,9 @@ export function VotesTokenImport(props: ICreationStepProps) {
         helper={t('helperTokenSupply')}
         isRequired
       >
-        {/* @todo: this allows alphanumeric input. intentional? */}
         <Input
           value={values.erc20Token.tokenSupply.bigintValue?.toString()}
+          readOnly
```
Comment (adamgall) [inline src/components/DaoCreator/formComponents/VotesTokenImport.tsx:53]: Agree with @tomstuart123 that this should make the input _look_ disabled

**Review by adamgall — CHANGES_REQUESTED** [review]

**Review by adamgall — APPROVED** [review]
i'll give this a quick approval from the code-review pov.

i haven't opened the app about it yet though so @tomstuart123 can you do that side?

**Comment by tomstuart123** [comment]
Looks good to me, thanks @DarksightKellar 

Screenshot 2024-06-14 at 20 10 59

**Review by tomstuart123 — APPROVED** [review]
