### PR TITLE
`Roles 0.1.0` desktop and other updates

### LINKED ISSUE #2090: `roles.0.1.0` Bug. Create Form
When opening the drawer in the create proposal screen for roles. the description and role name show for wrong role when there are multiple roles. This is caused by a index value that isn't correct

### PR DESCRIPTION
**Pull request by Da-Colon**
Knock a few different things in this PR. 

- Added Desktop Drawer for Role Details
- Added Click to open drawer on Role Proposal Creation
- Fixed Bugs:
  - Proposal Summary Running into Sidebar (Desktop
  - Missing Translations
  - Fixed Loading Card from changing Height
  - Fixed Position of Loading Card on Desktop
  - Fixed 'No Roles' display from showing up when its not suppose to
  - Fixed Role being removed when closing already edited New Role
  - Fixed Navigation to and from details and Edit
- Added Navigation from Details -> Edit

Closes #2090

### CODE REVIEW

File: src/components/pages/Roles/RolesDetailsDrawerMobile.tsx
Comment (Da-Colon) [inline src/components/pages/Roles/RolesDetailsDrawerMobile.tsx:1]: This basically just moves @mudrila work into its own file to make the `details/index` easier to follow with the two different drawers

File: src/constants/routes.ts [hunk 1]
```diff
@@ -6,7 +8,10 @@ export const BASE_ROUTES = {
 const getDaoQueryParam = (addressPrefix: string, daoAddress: string) =>
   `?dao=${addressPrefix}:${daoAddress}`;
 
-const getRoleQueryParam = (addressPrefix: string, daoAddress: string, hatIndex: number) =>
+const getRoleQueryParam = (addressPrefix: string, daoAddress: string, hatId: Hex) =>
+  `${getDaoQueryParam(addressPrefix, daoAddress)}&hatId=${hatId}`;
+
+const getRoleEditQueryParam = (addressPrefix: string, daoAddress: string, hatIndex: number) =>
   `${getDaoQueryParam(addressPrefix, daoAddress)}&hatIndex=${hatIndex}`;
```
Comment (Da-Colon) [inline src/constants/routes.ts:15]: For Editing, We use the HatIndex. This will allow for navigation from Role Details straight to Role Editing the proper Role

For Role Viewing, We use the HatId.

Comment (adamgall) [reply src/constants/routes.ts:15]: Why not use HatIndex for both cases?

**Review by tomstuart123 — APPROVED** [review]
As mentioned at standup, approving this for now based on this thread https://decentdao.slack.com/archives/C06QZTUTKRC/p1720351954501429

Will get do another round of testing on this once merged into root.

File: src/components/pages/Roles/RolesDetailsDrawer.tsx [hunk 2]
```diff
@@ -0,0 +1,168 @@
...
+  onEdit,
+}: RoleDetailsDrawerProps) {
+  const {
+    node: { daoAddress },
+  } = useFractal();
+  const { addressPrefix } = useNetworkConfig();
+  const { t } = useTranslation(['roles']);
+  const navigate = useNavigate();
+  const { daoName: accountDisplayName } = useGetDAOName({
+    address: getAddress(roleHat.wearer || zeroAddress),
```
Comment (adamgall) [inline src/components/pages/Roles/RolesDetailsDrawer.tsx:66]: `|| zeroAddress` can be removed after change above.

File: src/components/pages/Roles/RolesDetailsDrawer.tsx [hunk 3]
```diff
@@ -0,0 +1,168 @@
...
+    chainId: getChainIdFromPrefix(addressPrefix),
```
Comment (adamgall) [inline src/components/pages/Roles/RolesDetailsDrawer.tsx:67]: nit: pull the `chain.id` directly out of `useNetworkConfig`, and don't use `getChainIdFromPrefix()`

File: src/components/pages/Roles/RolesDetailsDrawer.tsx [hunk 4]
```diff
@@ -0,0 +1,168 @@
...
+  });
+  const avatarURL = useAvatar(roleHat.wearer || zeroAddress);
```
Comment (adamgall) [inline src/components/pages/Roles/RolesDetailsDrawer.tsx:69]: Can remove `|| zeroAddress` after type change above

File: src/components/pages/Roles/RolesDetailsDrawerMobile.tsx [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+import { useFractal } from '../../../providers/App/AppProvider';
+import { DecentRoleHat, useRolesState } from '../../../state/useRolesState';
+import DraggableDrawer from '../../ui/containers/DraggableDrawer';
+import { AvatarAndRoleName } from './RoleCard';
+import { SablierVesting, SablierPayroll, RoleValue } from './types';
+
+interface RoleDetailsDrawerMobileProps {
+  roleHat:
+    | (DecentRoleHat & { vestingData?: SablierVesting; payrollData?: SablierPayroll })
+    | RoleValue;
```
Comment (adamgall) [inline src/components/pages/Roles/RolesDetailsDrawerMobile.tsx:14]: Change this type to the same one from `RolesDetailDrawer`

File: src/components/pages/Roles/RolesTable.tsx [hunk 6]
```diff
@@ -280,46 +281,49 @@ export function RolesRowEdit({
...
-  roleHats: DecentRoleHat[];
-}) {
+export function RolesTable({ handleRoleClick }: { handleRoleClick: (hatId: Address) => void }) {
+  const { hatsTree } = useRolesState();
+  if (hatsTree === undefined) {
+    return <RoleCardLoading />;
+  }
+  if (hatsTree === null) {
+    return <RoleCardNoRoles />;
+  }
```
Comment (adamgall) [inline src/components/pages/Roles/RolesTable.tsx:291]: Ooh I like this

File: src/components/pages/Roles/RolesTable.tsx [hunk 7]
```diff
@@ -280,46 +281,49 @@ export function RolesRowEdit({
...
+                key={role.id.toString()}
+                hatId={role.id}
+                wearerAddress={role.wearer}
+                handleRoleClick={handleRoleClick}
+                {...role}
+              />
+            ))}
+          </Tbody>
+        </Table>
+      )}
```
Comment (adamgall) [inline src/components/pages/Roles/RolesTable.tsx:326]: Nit: plz DRY this table and the one from the Edit component into a function that receives the body rows (view, or edit), and returns the full table. I just want this dried up a bit

File: src/constants/routes.ts (hunk 1 above)
Comment (adamgall) [reply src/constants/routes.ts:15]: No sorry, I mean, it sounds like using Index is safer bet. So, why are we still using the HatId for Role Viewing?

File: src/pages/daos/[daoAddress]/roles/edit/index.tsx [hunk 8]
```diff
@@ -48,6 +54,25 @@ function RolesEdit() {
...
+    ).length;
+    const removedHatsCount = filteredHats.filter(
+      hat => hat.editedRole!.status === EditBadgeStatus.Removed,
+    ).length;
+
+    const addedHatsText = addedHatsCount > 0 ? t('addedHats', { addedHatsCount }) : '';
+    const updatedHatsText = updatedHatsCount > 0 ? t('updatedHats', { updatedHatsCount }) : '';
+    const removedHatsText = removedHatsCount > 0 ? t('removedHats', { removedHatsCount }) : '';
+
+    return [addedHatsText, updatedHatsText, removedHatsText].filter(Boolean).join('. ');
```
Comment (adamgall) [inline src/pages/daos/[daoAddress]/roles/edit/index.tsx:73]: wat is `.filter(Boolean)`

**Review by adamgall — CHANGES_REQUESTED** [review]

File: src/pages/daos/[daoAddress]/roles/edit/index.tsx (hunk 8 above)
Comment (Da-Colon) [reply src/pages/daos/[daoAddress]/roles/edit/index.tsx:73]: it part filters out any falsy values from the array

File: src/pages/daos/[daoAddress]/roles/edit/details/index.tsx [hunk 9]
```diff
@@ -100,6 +101,32 @@ export default function RoleEditDetails() {
...
+                  >
+                    <Flex
+                      gap="1rem"
+                      alignItems="center"
+                    >
+                      <IconButton
+                        variant="tertiary"
+                        size="icon-sm"
+                        aria-label="Close Drawer"
+                        as={X}
```
[the remark this answers is not in the document]
Comment (Da-Colon) [reply src/pages/daos/[daoAddress]/roles/edit/details/index.tsx:116]: I don't know, I think I just had got done create a `Icon` component and used `as` ha. I'll updated it

**Comment by nicolaus-sherrill** [comment]
Can’t scroll on mobile browser.

I-phone 12
Aloha browser & Safari
<details><summary>Browser metadata</summary>





```
Path:      /roles/edit/details?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD&hatIndex=0
Browser:   Safari 17.5.1 on iOS 17.5.1
Viewport:  390 x 671 @3x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2081.app.dev.decentdao.org%2Froles%2Fedit%2Fdetails%3Fdao%3Dsep%3A0xe20221A8939F9373C091262CBEF9493aca196acD%26hatIndex%3D0&os=iOS&os_version=17.5&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2081.app.dev.decentdao.org/roles/edit/details?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD&hatIndex=0) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=668b30cffc4a0d0008ff3a94&commentID=668c0a9986b4e95a46541dad&resolution=resolved)

**Comment by nicolaus-sherrill** [comment]
Missing "New/Updated" UI chip for affected roles in the Edit Roles view.

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /roles/edit?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD
Browser:   Firefox 127.0 on Mac OS 10.15
Viewport:  1680 x 912 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2081.app.dev.decentdao.org%2Froles%2Fedit%3Fdao%3Dsep%3A0xe20221A8939F9373C091262CBEF9493aca196acD&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=127.0&resolution=1680x912&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2081.app.dev.decentdao.org/roles/edit?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=668b30cffc4a0d0008ff3a94&commentID=668c120427123c64ec6a5265&resolution=resolved)

**Comment by nicolaus-sherrill** [comment]
Proposal creation is failing when trying to add a new role.

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /roles/edit/summary?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD
Browser:   Firefox 127.0 on Mac OS 10.15
Viewport:  1680 x 912 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2081.app.dev.decentdao.org%2Froles%2Fedit%2Fsummary%3Fdao%3Dsep%3A0xe20221A8939F9373C091262CBEF9493aca196acD&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=127.0&resolution=1680x912&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2081.app.dev.decentdao.org/roles/edit/summary?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=668b30cffc4a0d0008ff3a94&commentID=668c12b3f646e316bc0f1a6d&resolution=resolved)

**Comment by nicolaus-sherrill** [comment]
Dynamic copy overrides any previous manual text input when user clicks away from the proposal editor.

recording


<details><summary>Browser metadata</summary>





```
Path:      /roles/edit/summary?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD
Browser:   Firefox 127.0 on Mac OS 10.15
Viewport:  1680 x 912 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2081.app.dev.decentdao.org%2Froles%2Fedit%2Fsummary%3Fdao%3Dsep%3A0xe20221A8939F9373C091262CBEF9493aca196acD&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=127.0&resolution=1680x912&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2081.app.dev.decentdao.org/roles/edit/summary?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=668b30cffc4a0d0008ff3a94&commentID=668c139fd4752666624f5fee&resolution=resolved)

**Comment by nicolaus-sherrill** [comment]
No warning modal to stop the user from losing their draft changes.

recording


<details><summary>Browser metadata</summary>





```
Path:      /roles?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD
Browser:   Firefox 127.0 on Mac OS 10.15
Viewport:  1680 x 912 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2081.app.dev.decentdao.org%2Froles%3Fdao%3Dsep%3A0xe20221A8939F9373C091262CBEF9493aca196acD&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=127.0&resolution=1680x912&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2081.app.dev.decentdao.org/roles?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=668b30cffc4a0d0008ff3a94&commentID=668c13e53bde7d6bcfeafa35&resolution=resolved)

**Review by adamgall — APPROVED** [review]
