### PR TITLE
`1932`  adds fallback compatibility for older and mobile browsers

### LINKED ISSUE #1932: "Copy address" behavior not working on mobile
Experienced on:
- Mobile Chromium
- iOS

### PR DESCRIPTION
**Pull request by Da-Colon**
Fixes #1932 

See: https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

### CODE REVIEW

File: src/hooks/utils/useCopyText.ts [hunk 1]
```diff
@@ -1,14 +1,35 @@
...
+        document.body.appendChild(textArea);
+        textArea.focus();
+        textArea.select();
+        document.execCommand('copy');
+        document.body.removeChild(textArea);
+      }
+      toast(t('toastClipboardCopy'), { autoClose: 1000 });
+    } catch (error) {
+      console.error('Failed to copy text to clipboard: ', error);
+      toast(t('toastClipboardCopyError'), { autoClose: 1000 });
```
Comment (adamgall) [inline src/hooks/utils/useCopyText.ts:31]: Where da strings at

**Review by adamgall — CHANGES_REQUESTED** [review]

**Comment by adamgall** [comment]
The implementation works for me tho

File: src/hooks/utils/useCopyText.ts (hunk 1 above)
Comment (Da-Colon) [reply src/hooks/utils/useCopyText.ts:31]: Yep forgot to add the copy. I'll circle back in a bit

Comment (Da-Colon) [reply src/hooks/utils/useCopyText.ts:31]: would this change be acceptable, log the error for sentry and use the general error copy? As this would be an unexpected error if it were to occur.
```
logError(error);
toast(t('errorGeneral'), { autoClose: 1000 });
```

Comment (adamgall) [reply src/hooks/utils/useCopyText.ts:31]: @Da-Colon I think it's appropriate to use a specific error string here, because we're capturing this specific error. Let's just add a new error string to the localization.

I'll do it and push a commit.

**Review by adamgall — APPROVED** [review]
