### PR TITLE
Use `fallbackTokenData`

### LINKED ISSUE #2369: On Treasury page, safe governance token shows as "ETH" instead of the token symbol
Steps to see the problem:

Check out [this safe's treasury page](https://app.dev.decentdao.org/treasury?dao=sep:0xa042F2b97855f72c4714B9E5ff9d603D2EE7F078). Nothing obvious amiss here, except:
- The "ETH" tx is actually meant to be [the safe's governance token](https://sepolia.etherscan.io/tx/0xd5457aac85e3171621757a461505127fc3b52f9097976e72933c36128414cf32)

Likely culprit is this exception from safe api:
Image

### PR DESCRIPTION
**Pull request by DarksightKellar**
Closes #2369 (~kinda~ fr)

This PR implements a fallback for transferred token data when `safeAPI.getToken` throws.

The cause of the "no token matches given query" exception is still unclear, as the address is quite clearly on etherscan (and Moralis returns its balance if the safe has some). ~While this fallback works for safes that have _some_ balance of the problem token, it doesn't for safes that have a 0-balance even if they at one time had some.~ The fallback retrieves token info from the blockchain directly.

Also the `setTimeout` retry in case of rate limited error was removed because I'm not sure about the end result of this PR yet and didn't want to commit to a lengthy refactor at this point. If needed, this functionality can be restored in some form during review.

### CODE REVIEW

File: src/hooks/DAO/loaders/useDecentTreasury.ts [hunk 1]
```diff
@@ -132,17 +132,30 @@ export const useDecentTreasury = () => {
 
     // Instead of this block of code, check the commented out snippet
     // below this for a half-implemented alternative.
-    const tokenData = await Promise.all(
-      tokenAddresses.map(async addr => {
+    const transfersTokenInfo = await Promise.all(
+      tokenAddressesOfTransfers.map(async addr => {
```
Comment (mudrila) [inline src/hooks/DAO/loaders/useDecentTreasury.ts:136]: Is there other `address` variable in the scope? Why just not naming it `address`?

File: src/hooks/DAO/loaders/useDecentTreasury.ts [hunk 2]
```diff
@@ -132,17 +132,30 @@ export const useDecentTreasury = () => {
...
+              address: addr,
+              name: 'Unknown',
+              symbol: '???',
+              decimals: 18,
+            };
+          }
+
+          return {
+            address: addr,
+            name: fallbackTokenData?.name,
```
Comment (mudrila) [inline src/hooks/DAO/loaders/useDecentTreasury.ts:154]: Seems like this optional chaining is redundant - we already doing early return

File: src/hooks/DAO/loaders/useDecentTreasury.ts [hunk 3]
```diff
@@ -132,17 +132,30 @@ export const useDecentTreasury = () => {
...
-              return safeAPI.getToken(addr);
-            }
-          }, 300);
+          const fallbackTokenData = tokenBalances?.find(
+            tokenBalanceData => getAddress(tokenBalanceData.tokenAddress) === addr,
+          );
+          if (!fallbackTokenData) {
+            return {
+              address: addr,
+              name: 'Unknown',
```
Comment (mudrila) [inline src/hooks/DAO/loaders/useDecentTreasury.ts:146]: Wondering if that makes sense to also add some sort of tooltip in place where we're displaying to outline that we weren't able to load token metadata

File: src/hooks/DAO/loaders/useDecentTreasury.ts [hunk 4]
```diff
@@ -132,17 +132,30 @@ export const useDecentTreasury = () => {
...
+              symbol: '???',
```
Comment (mudrila) [inline src/hooks/DAO/loaders/useDecentTreasury.ts:147]: I'd suggest using `---` instead - but that's just "my personal user preference" - kinda makes more sense to me personally that `---` means we weren't able to fetch something in comparison to `???` which for me means "some unexpected shit is going on"

**Review by mudrila — COMMENTED** [review]
Some comments sir - but mostly code styling / "my user feedback" - so feel free to reason your vision and I'll approve :)

File: src/hooks/DAO/loaders/useDecentTreasury.ts (hunk 1 above)
Comment (DarksightKellar) [reply src/hooks/DAO/loaders/useDecentTreasury.ts:136]: Because `address` on its own doesn't say anything about what and where these addresses came from

File: src/hooks/DAO/loaders/useDecentTreasury.ts (hunk 2 above)
Comment (DarksightKellar) [reply src/hooks/DAO/loaders/useDecentTreasury.ts:154]: True

File: src/hooks/DAO/loaders/useDecentTreasury.ts (hunk 4 above)
Comment (DarksightKellar) [reply src/hooks/DAO/loaders/useDecentTreasury.ts:147]: Wholeheartedly agree

File: src/hooks/DAO/loaders/useDecentTreasury.ts (hunk 3 above)
Comment (DarksightKellar) [reply src/hooks/DAO/loaders/useDecentTreasury.ts:146]: idk tbh. And I also don't know if this is worth pursuing if this issue is potentially a testnet only problem

**Comment by DarksightKellar** [comment]
@decentdao/engineering Looking for feedback re:
> Also the `setTimeout` retry in case of rate limited error was removed because I'm not sure about the end result of this PR yet and didn't want to commit to a lengthy refactor at this point. If needed, this functionality can be restored in some form during review

See diff on `140`

File: src/hooks/DAO/loaders/useDecentTreasury.ts (hunk 1 above)
Comment (mudrila) [reply src/hooks/DAO/loaders/useDecentTreasury.ts:136]: I'd say neither `addr` - that's why either suggesting not shortcutting or putting proper variable naming
But this one is super minor - I just personally don't line shortcut variable naming - feel free to ignore :)

Comment (DarksightKellar) [reply src/hooks/DAO/loaders/useDecentTreasury.ts:136]: oh lmaooo you meant the `addr` _in the callback_. That wasn't diff from this PR so didn't realise that's what you were referring to. Thought you meant `tokenAddressesOfTransfers` which is what I'd updated.

I mean, I don't mind it but sure I can update it too.

File: src/hooks/DAO/loaders/useDecentTreasury.ts [hunk 5]
```diff
@@ -132,17 +132,30 @@ export const useDecentTreasury = () => {
...
-              return safeAPI.getToken(addr);
-            }
-          }, 300);
+          const fallbackTokenData = tokenBalances?.find(
+            tokenBalanceData => getAddress(tokenBalanceData.tokenAddress) === address,
+          );
+          if (!fallbackTokenData) {
+            return {
+              address,
+              name: 'Unknown',
```
Comment (adamgall) [inline src/hooks/DAO/loaders/useDecentTreasury.ts:146]: Nitpicky but let's put this "Unknown" string into a localization file

**Review by adamgall — CHANGES_REQUESTED** [review]

File: src/hooks/DAO/loaders/useDecentTreasury.ts [hunk 6]
```diff
@@ -132,17 +132,30 @@ export const useDecentTreasury = () => {
...
+              symbol: '---',
+              decimals: 18,
```
Comment (adamgall) [inline src/hooks/DAO/loaders/useDecentTreasury.ts:148]: Also, we don't know that this unknown token is actually 18 decimal places, right?

I'm almost thinking that maybe we just straight up _ignore_ any transfer records where attempting to get the token data from Safe API fails, instead of attempting to backfill those records with dummy data.

**Review by adamgall — APPROVED** [review]

File: src/hooks/DAO/loaders/useDecentTreasury.ts (hunk 3 above)
Comment (DarksightKellar) [reply src/hooks/DAO/loaders/useDecentTreasury.ts]: No longer an issue after [this commit](https://github.com/decentdao/decent-interface/pull/2377/commits/c74d5ce11cd8f4bec83fab412917886e6ecde2a9)

File: src/hooks/DAO/loaders/useDecentTreasury.ts (hunk 5 above)
Comment (DarksightKellar) [reply src/hooks/DAO/loaders/useDecentTreasury.ts]: Resolved in [this commit](https://github.com/decentdao/decent-interface/pull/2377/commits/c74d5ce11cd8f4bec83fab412917886e6ecde2a9). And, whew.

**Review by mudrila — APPROVED** [review]
Lezzgooo
