### PR TITLE
Fix redirect loaders

### LINKED ISSUE #2381: Redirect loaders in `router.tsx` aren't working (`daoAddress` param is `undefined` which leads to wrong redirect)

### PR DESCRIPTION
**Pull request by mudrila**
Closes #2381

### CODE REVIEW

File: src/main.tsx [hunk 1]
```diff
@@ -1,26 +1,32 @@
...
 
-function FractalRouterProvider() {
+function DecentRouterProvider() {
   const { addressPrefix } = useNetworkConfig();
-  return <RouterProvider router={router(addressPrefix)} />;
+  const urlParams = new URLSearchParams(window.location.search);
+  const addressWithPrefix = urlParams.get('dao');
+
+  const prefixAndAddress = addressWithPrefix?.split(':');
+  const daoAddressStr = prefixAndAddress?.[1];
```
Comment (adamgall) [inline src/main.tsx:19]: Considering this is all classified as "user input", do we need to do any sanitization on this data?

**Review by adamgall — APPROVED** [review]

File: src/main.tsx (hunk 1 above)
Comment (mudrila) [reply src/main.tsx:19]: Well, sanitization kinda gonna happen anyway after the redirect through the logic of fetching DAO - so I feel like doing it here as well to prevent redirect / redirect to app homepage is kinda redundant - we'll be taking from the user ability to see that there's something wrong with the address
