### PR TITLE
No tab selection

### LINKED ISSUE #2170: Tab navigation breaks proposal preview.
recording

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /home?dao=eth:0xB98d45F9021D71E6Fc30b43FD37FB3b1Bf12c064
Browser:   Chrome 126.0.0.0 on Mac OS 10.15.7
Viewport:  1680 x 904 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2165.app.dev.decentdao.org%2Fhome%3Fdao%3Deth%3A0xB98d45F9021D71E6Fc30b43FD37FB3b1Bf12c064&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=126.0&resolution=1680x904&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #2165](https://deploy-preview-2165.app.dev.decentdao.org/home?dao=eth:0xB98d45F9021D71E6Fc30b43FD37FB3b1Bf12c064)

### PR DESCRIPTION
**Pull request by adamgall**
Fixes #2170

When proposal descriptions are being displayed in the "collapsed" view (like on the Dashboard, and Proposal pages), using tab to cycle through links in the page will not include the links in the proposal description which are hidden in the collapsed view, which was causing rendering bugs (see video in issue).

Tab selection behavior is unchanged on Proposal Details view. Still want links in that view to be selectable via tab.

### CODE REVIEW

File: src/components/ui/proposal/Markdown.tsx [hunk 1]
```diff
@@ -87,25 +139,38 @@ export default function Markdown({
...
-            components={MarkdownComponents}
-            className="markdown-body"
-          >
-            {content}
-          </ReactMarkdown>
-        )}
-      </Box>
+      {collapsed ? (
+        <MarkdowContentWithoutTabs
+          collapsed={collapsed}
```
Comment (DarksightKellar) [inline src/components/ui/proposal/Markdown.tsx:157]: Might as well do `collapsed={true}` here

File: src/components/ui/proposal/Markdown.tsx [hunk 2]
```diff
@@ -87,25 +139,38 @@ export default function Markdown({
...
+          truncate={truncate}
+          collapsedLines={collapsedLines}
+          markdownTextContainerRef={markdownTextContainerRef}
+        >
+          {innerContent}
+        </MarkdowContentWithoutTabs>
+      ) : (
+        <MarkdowContentWithTabs
+          collapsed={collapsed}
```
Comment (DarksightKellar) [inline src/components/ui/proposal/Markdown.tsx:166]: And `collapsed={false}` here

**Review by DarksightKellar — CHANGES_REQUESTED** [review]

**Review by tomstuart123 — APPROVED** [review]
nice @adamgall works for me and good catch @nicolaus-sherrill

File: src/components/ui/proposal/Markdown.tsx (hunk 1 above)
Comment (adamgall) [reply src/components/ui/proposal/Markdown.tsx:157]: good call

File: src/components/ui/proposal/Markdown.tsx (hunk 2 above)
Comment (adamgall) [reply src/components/ui/proposal/Markdown.tsx:166]: good call

**Review by DarksightKellar — APPROVED** [review]
