### PR TITLE
`2129` Drawer Closing Bug

### LINKED ISSUE #2129: Closing edit role drawer remove it from roles list
Begin editing roles, click a role to edit it. With or without making changes, click outside the drawer to close it. The role disappears from the list.

### PR DESCRIPTION
**Pull request by Da-Colon**
Fixes #2129

### CODE REVIEW

File: src/pages/daos/[daoAddress]/roles/edit/details/index.tsx [hunk 1]
```diff
@@ -193,7 +193,7 @@ export default function RoleEditDetails() {
               isOpen
               placement="right"
               onClose={() => {
-                if (hatIndex !== -1) {
+                if (hatIndex === -1) {
```
Comment (DarksightKellar) [inline src/pages/daos/[daoAddress]/roles/edit/details/index.tsx:196]: lmaooo

**Review by DarksightKellar — APPROVED** [review]

**Review by adamgall — APPROVED** [review]
