### PR TITLE
Fix amount per week

### LINKED ISSUE #2266: Bug: Bigint RangeError
Image

```ts
   const amountPerWeek = useMemo(()=>{
        if (!payment.amount?.bigintValue || !payment.startDate || !payment.endDate) {
            return;
        }
        const endTime = payment.endDate.getTime() / 1000;
        const startTime = payment.startDate.getTime() / 1000;
        const totalSeconds = endTime - startTime;
        const amountPerSecond = payment.amount.bigintValue / BigInt(totalSeconds);
        const secondsInWeek = BigInt(60 * 60 * 24 * 7);
        return amountPerSecond * secondsInWeek;
    }
    , [payment]);
```

fails at `amountPerSecond`.

### PR DESCRIPTION
**Pull request by mudrila**
Closes #2266

### CODE REVIEW

File: src/components/pages/Roles/RolePaymentDetails.tsx [hunk 1]
```diff
@@ -127,7 +127,7 @@ export function RolePaymentDetails({
 
     const endTime = payment.endDate.getTime() / 1000;
     const startTime = payment.startDate.getTime() / 1000;
-    const totalSeconds = endTime - startTime;
+    const totalSeconds = Math.round(endTime - startTime); // @dev due to milliseconds we need to round it to avoid problems with BigInt
```
Comment (adamgall) [inline src/components/pages/Roles/RolePaymentDetails.tsx:130]: of course! thank you

**Review by adamgall — APPROVED** [review]
